version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd packaging-and-delivery-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t packaging-and-delivery-services .
      - docker tag packaging-and-delivery-service 860061945305.dkr.ecr.us-east-1.amazonaws.com/adithya-package:PackagingAndDeliveryServices
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push 860061945305.dkr.ecr.us-east-1.amazonaws.com/adithya-package:PackagingAndDeliveryServices
      - echo Writing definition files
      - printf '[{"name":"PackagingAndDeliveryService-container","imageUri":"%s"}]' 860061945305.dkr.ecr.us-east-1.amazonaws.com/adithya-package:PackagingAndDeliveryServices > taskdefinition.json

artifacts:
  files: packaging-and-delivery-service/taskdefinition.json


