version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd Component-Processing-Service
      - mvn clean package
      - echo Building the docker image
      - docker build -t component-processing-services .
      - docker tag component-processing-service 860061945305.dkr.ecr.us-east-1.amazonaws.com/adithya-component:component-processing-services
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push 860061945305.dkr.ecr.us-east-1.amazonaws.com/adithya-component:component-processing-services
      - echo Writing definition files
      - printf '[{"name":"component-processing-service-container","imageUri":"%s"}]' 860061945305.dkr.ecr.us-east-1.amazonaws.com/adithya-component:component-processing-services > taskdefinition.json

artifacts:
  files: Component-Processing-Service/taskdefinition.json


