version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd Authentication-Service
      - mvn clean package
      - echo Building the docker image
      - docker build -t authappimage .
      - docker tag authapp ecr
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push ecr
      - echo Writing definition files
      - printf '[{"name":"authapp-container","imageUri":"%s"}]' ecr > taskdefinition.json

artifacts:
  files: Authentication-Service/taskdefinition.json


